(function(){
'use strict';
if(window.__nethorPageEditorLoaded)return;window.__nethorPageEditorLoaded=true;
const U='https://gioxrpaiwogqqtakjpnv.supabase.co',K='sb_publishable_nJPMS-Z_20ng1aMJmufbmg_gWFFndrC';
let client=null,session=null,editing=false,dirty=false,layouts={},backupLayouts=null,observer=null,timer=0,interaction=null;
const pageKey=()=>{const p=location.pathname.split('/').pop()||'home.html';return p.split('?')[0]||'home.html'};
const platform=()=>String(document.documentElement.dataset.nethorPlatform||window.NethorPlatform?.current?.()||'desktop').toLowerCase()==='mobile'?'mobile':'desktop';
const selector='[data-nethor-widget],[data-widget-id],.ndCard,.ndKpi,.ndHeroSlot,.ndPlanningSlot,.ndSideStack,.mhdCard,.mhdSection,.mhdWidget,.operationsWidgetAdminCard,.quickPlanningWidget,.storeInfoWidget';
function candidate(el){if(!(el instanceof HTMLElement)||el.closest('#nethorPageEditorUI'))return false;if(el.matches('button,a,input,select,textarea,nav,header,footer'))return false;const r=el.getBoundingClientRect();return r.width>90&&r.height>45}
function targets(){return [...document.querySelectorAll(selector)].filter(candidate).filter(el=>{const p=el.parentElement?.closest(selector);return !p||!candidate(p)})}
function label(el,i){const v=el.dataset.nethorWidget||el.dataset.widgetId||el.id;if(v)return v.replace(/^nethorDesktop/,'').replace(/Widget$/,'').replace(/[-_]/g,' ');const h=el.querySelector('h1,h2,h3,strong,.ndSectionTitle,.mhdTitleWithIcon');return String(h?.textContent||'Widget '+(i+1)).replace(/\s+/g,' ').trim().slice(0,48)}
function key(el,i){if(el.dataset.nethorEditorKey)return el.dataset.nethorEditorKey;const explicit=el.id||el.dataset.nethorWidget||el.dataset.widgetId;if(explicit)return 'id_'+explicit;const cls=[...el.classList].filter(x=>/^nd|^mhd|Widget|widget/i.test(x)).slice(0,3).join('_')||'widget';const slug=label(el,i).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');return 'auto_'+cls+'_'+slug}
function map(){layouts[pageKey()]=layouts[pageKey()]||{};layouts[pageKey()][platform()]=layouts[pageKey()][platform()]||{};return layouts[pageKey()][platform()]}
function apply(){
 if(editing)return;
 const m=map();targets().forEach((el,i)=>{const s=m[key(el,i)];if(el.dataset.nethorEditorApplied==='1')return;if(s?.width)el.style.width=s.width+'px';if(s?.height)el.style.height=s.height+'px';el.dataset.nethorEditorApplied='1';if(s&&(s.x||s.y))el.style.transform='translate3d('+Number(s.x||0)+'px,'+Number(s.y||0)+'px,0)'})
}
function ensureUI(){if(document.getElementById('nethorPageEditorUI'))return;const w=document.createElement('div');w.id='nethorPageEditorUI';w.innerHTML='<button type="button" class="nethorPageEditorButton" id="nethorPageEditorButton" aria-label="Modifier la page" title="Modifier la page"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m4 16.5-.8 3.8 3.8-.8L18.7 7.8a2.7 2.7 0 0 0-3.8-3.8L3.2 16.2Z"/><path d="m13.5 5.7 4.8 4.8"/></svg></button>';document.body.appendChild(w);w.firstElementChild.onclick=()=>editing?finish(false):start()}
function bar(){const b=document.createElement('div');b.className='nethorPageEditorBar';b.id='nethorPageEditorBar';b.innerHTML='<span class="nethorPageEditorHint">Mode édition · déplace ou redimensionne les widgets</span><button type="button" class="cancel">Annuler</button><button type="button" class="save">Enregistrer</button>';document.body.appendChild(b);b.querySelector('.cancel').onclick=()=>finish(true);b.querySelector('.save').onclick=save}
function render(){
 if(interaction)return;
 document.querySelectorAll('.nethorPageEditorTarget').forEach(x=>x.classList.remove('nethorPageEditorTarget','is-selected'));
 document.querySelectorAll('.nethorPageEditorHandle').forEach(x=>x.remove());
 const m=map();targets().forEach((el,i)=>{if(el.classList.contains('nethorPageEditorTarget'))return;const k=key(el,i),s=m[k]||{};el.dataset.nethorEditorKey=k;el.dataset.nethorEditorLabel=label(el,i);el.classList.add('nethorPageEditorTarget');if(s.width)el.style.width=s.width+'px';if(s.height)el.style.height=s.height+'px';if(s.x||s.y)el.style.transform='translate3d('+Number(s.x||0)+'px,'+Number(s.y||0)+'px,0)';const h=document.createElement('span');h.className='nethorPageEditorHandle';el.appendChild(h);el.onpointerdown=down});
}
function start(){backupLayouts=JSON.parse(JSON.stringify(layouts));editing=true;dirty=false;document.documentElement.classList.add('nethorPageEditorOpen');document.getElementById('nethorPageEditorButton')?.classList.add('is-active');bar();render()}
function finish(cancel){editing=false;interaction=null;document.documentElement.classList.remove('nethorPageEditorOpen');document.getElementById('nethorPageEditorBar')?.remove();document.getElementById('nethorPageEditorButton')?.classList.remove('is-active');document.querySelectorAll('.nethorPageEditorHandle').forEach(x=>x.remove());document.querySelectorAll('.nethorPageEditorTarget').forEach(x=>{x.classList.remove('nethorPageEditorTarget','is-selected');x.removeAttribute('data-nethor-editor-label')});if(cancel){layouts=backupLayouts||layouts;document.querySelectorAll('[data-nethor-editor-key]').forEach(el=>{el.dataset.nethorEditorApplied='';el.style.removeProperty('width');el.style.removeProperty('height');el.style.removeProperty('transform')});apply()}dirty=false;backupLayouts=null}
function read(el){let x=0,y=0;const t=getComputedStyle(el).transform;if(t&&t!=='none'){const m=new DOMMatrix(t);x=m.m41;y=m.m42}const r=el.getBoundingClientRect();map()[el.dataset.nethorEditorKey]={x:Math.round(x),y:Math.round(y),width:Math.round(r.width),height:Math.round(r.height)};dirty=true}
function down(e){if(!editing||e.button!==0)return;const el=e.currentTarget;if(e.target.classList.contains('nethorPageEditorHandle')){resize(el,e);return}e.preventDefault();e.stopPropagation();interaction=el;el.classList.add('is-selected');let bx=0,by=0;const t=getComputedStyle(el).transform;if(t&&t!=='none'){const m=new DOMMatrix(t);bx=m.m41;by=m.m42}const sx=e.clientX,sy=e.clientY;const move=v=>{el.style.transform='translate3d('+Math.round(bx+v.clientX-sx)+'px,'+Math.round(by+v.clientY-sy)+'px,0)';dirty=true};const up=()=>{document.removeEventListener('pointermove',move);interaction=null;read(el)};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up,{once:true})}
function resize(el,e){e.preventDefault();e.stopPropagation();interaction=el;const r=el.getBoundingClientRect(),sx=e.clientX,sy=e.clientY,bw=r.width,bh=r.height;const move=v=>{el.style.width=Math.max(120,Math.round(bw+v.clientX-sx))+'px';el.style.height=Math.max(60,Math.round(bh+v.clientY-sy))+'px';dirty=true};const up=()=>{document.removeEventListener('pointermove',move);read(el)};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up,{once:true})}
async function save(){const btn=document.querySelector('.nethorPageEditorBar .save');if(btn)btn.disabled=true;try{const {data,error}=await client.from('app_settings').select('value').eq('key','site_config').maybeSingle();if(error)throw error;const cfg=data?.value&&typeof data.value==='object'?JSON.parse(JSON.stringify(data.value)):{};cfg.page_editor=cfg.page_editor&&typeof cfg.page_editor==='object'?cfg.page_editor:{};cfg.page_editor.layouts=cfg.page_editor.layouts&&typeof cfg.page_editor.layouts==='object'?cfg.page_editor.layouts:{};cfg.page_editor.layouts[pageKey()]=layouts[pageKey()];const {error:e}=await client.from('app_settings').upsert({key:'site_config',value:cfg,updated_by:session.user.id,updated_at:new Date().toISOString()},{onConflict:'key'});if(e)throw e;layouts=cfg.page_editor.layouts;window.NettoSounds?.play?.('success');finish(false)}catch(e){console.error(e);alert('Impossible d’enregistrer la mise en page.');if(btn)btn.disabled=false}}
function watch(){if(interaction)return;clearTimeout(timer);timer=setTimeout(()=>{if(interaction)return;editing?render():apply()},250)}
async function boot(){if(!window.supabase?.createClient)return;try{client=window.supabase.createClient(U,K,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data:{session:s}}=await client.auth.getSession();session=s;if(!session)return;const {data:p}=await client.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(p?.role!=='admin')return;const {data:setting}=await client.from('app_settings').select('value').eq('key','site_config').maybeSingle();layouts=setting?.value?.page_editor?.layouts||{};ensureUI();apply();observer=new MutationObserver(watch);observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('resize',()=>{if(!editing)watch()},{passive:true});document.addEventListener('click',e=>{if(!editing)return;if(e.target.closest('#nethorPageEditorUI,#nethorPageEditorBar'))return;if(e.target.closest('.nethorPageEditorTarget')){e.preventDefault();e.stopImmediatePropagation()}},true)}catch(e){console.warn('Éditeur Nethor:',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,900),{once:true});else setTimeout(boot,900);
})();