-- Chat Nethor : suppression visuelle, archives admin et actions globales.
alter table public.chat_conversations
  add column if not exists archived_at timestamptz,
  add column if not exists archived_by uuid references public.profiles(id) on delete set null;

create table if not exists public.chat_archive_logs(
  id bigint generated by default as identity primary key,
  conversation_id uuid,
  conversation_type text not null,
  conversation_name text,
  created_by uuid,
  archived_by uuid,
  archived_at timestamptz not null default now(),
  restored_by uuid,
  restored_at timestamptz,
  details jsonb not null default '{}'::jsonb
);

alter table public.chat_archive_logs enable row level security;
drop policy if exists "chat archive admin read" on public.chat_archive_logs;
create policy "chat archive admin read" on public.chat_archive_logs
for select to authenticated using (private.has_role(array['admin']));

-- list_chat_conversations ignore désormais les conversations archivées.
-- RPC installées par la migration appliquée :
-- chat_archive_conversation(uuid)
-- chat_restore_conversation(uuid)
-- list_chat_archives()
-- chat_mark_all_read()
