-- Nethor — signalement de problèmes utilisateurs
-- 2026-09-28

create table if not exists public.reported_problems (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reporter_name text not null default 'Utilisateur',
  reporter_role text,
  description text not null check (char_length(btrim(description)) between 8 and 2000),
  source_path text,
  source_title text,
  user_agent text,
  status text not null default 'new' check (status in ('new','in_progress','resolved')),
  admin_note text,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reported_problems_reporter_idx
  on public.reported_problems(reporter_id);

create index if not exists reported_problems_status_created_idx
  on public.reported_problems(status, created_at desc);

alter table public.reported_problems enable row level security;

grant select, insert, update, delete on public.reported_problems to authenticated;
grant usage, select on sequence public.reported_problems_id_seq to authenticated;

drop policy if exists "reported_problems_insert_own" on public.reported_problems;
create policy "reported_problems_insert_own"
on public.reported_problems
for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and (select auth.uid()) = reporter_id
);

drop policy if exists "reported_problems_select_own_or_admin" on public.reported_problems;
create policy "reported_problems_select_own_or_admin"
on public.reported_problems
for select
to authenticated
using (
  (select auth.uid()) = reporter_id
  or (select private.has_role(array['admin'::text]))
);

drop policy if exists "reported_problems_admin_update" on public.reported_problems;
create policy "reported_problems_admin_update"
on public.reported_problems
for update
to authenticated
using ((select private.has_role(array['admin'::text])))
with check ((select private.has_role(array['admin'::text])));

drop policy if exists "reported_problems_admin_delete" on public.reported_problems;
create policy "reported_problems_admin_delete"
on public.reported_problems
for delete
to authenticated
using ((select private.has_role(array['admin'::text])));
